services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
        - "127.0.0.1:15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - internal

  redis:
    image: redis:latest
    container_name: kraeved_redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:16379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - internal


  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kraeved_api
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "18000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/api/ping')\"",
        ]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 10
    networks:
      - internal
      - shared_proxy
volumes:
  pgdata:
  redisdata:

networks:
  internal:
    driver: bridge
  shared_proxy:
    name: shared_proxy
    external: true
