"""v3 init — all tables from scratch

Revision ID: 590c3d83b803
Revises:
Create Date: 2026-03-22
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "590c3d83b803"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_regions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('country', 'region', 'city', 'district', name='geo_region_type_enum'), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('polygon', sa.Text(), nullable=True),
    sa.Column('centroid', sa.Text(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['geo_regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_geo_regions_parent_id'), 'geo_regions', ['parent_id'], unique=False)
    op.create_table('interests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interests_emoji'), 'interests', ['emoji'], unique=False)
    op.create_index(op.f('ix_interests_name'), 'interests', ['name'], unique=True)
    op.create_table('prompt_compositions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scenario', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('scenario', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('transport_context', sa.String(), nullable=True),
    sa.Column('weather_context', sa.String(), nullable=True),
    sa.Column('group_context', sa.String(), nullable=True),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_category'), 'prompt_templates', ['category'], unique=False)
    op.create_index(op.f('ix_prompt_templates_slug'), 'prompt_templates', ['slug'], unique=True)
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('transport', 'food', 'activity', 'guide', 'other', name='service_type_enum'), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('interest', 'audience', 'format', 'season', name='tag_category_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('tourist', 'owner', 'both', name='user_role_enum'), server_default='tourist', nullable=False),
    sa.Column('taste_profile', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=True),
    sa.Column('required_distinct_posts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_achievements_interest_id'), 'achievements', ['interest_id'], unique=False)
    op.create_table('experts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('price_from', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('contacts', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('region_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['geo_regions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experts_region_id'), 'experts', ['region_id'], unique=False)
    op.create_index(op.f('ix_experts_user_id'), 'experts', ['user_id'], unique=False)
    op.create_table('filter_presets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('group_type', sa.String(), nullable=True),
    sa.Column('group_size', sa.Integer(), nullable=True),
    sa.Column('transport', sa.String(), nullable=True),
    sa.Column('budget', sa.String(), nullable=True),
    sa.Column('interests', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('pace', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filter_presets_user_id'), 'filter_presets', ['user_id'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_code'), 'invites', ['code'], unique=True)
    op.create_index(op.f('ix_invites_invitee_id'), 'invites', ['invitee_id'], unique=False)
    op.create_index(op.f('ix_invites_inviter_id'), 'invites', ['inviter_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('geo_lat', sa.Float(), nullable=True),
    sa.Column('geo_lng', sa.Float(), nullable=True),
    sa.Column('season', sa.Enum('spring', 'summer', 'autumn', 'winter', name='season_enum'), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('need_car', sa.Boolean(), nullable=False),
    sa.Column('price_level', sa.Enum('low', 'mid', 'high', name='price_level_enum'), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('best_angle', sa.Text(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['geo_regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_partner_id'), 'posts', ['partner_id'], unique=False)
    op.create_index(op.f('ix_posts_region_id'), 'posts', ['region_id'], unique=False)
    op.create_table('prompt_composition_items',
    sa.Column('composition_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.SmallInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['composition_id'], ['prompt_compositions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('composition_id', 'template_id')
    )
    op.create_index(op.f('ix_prompt_composition_items_composition_id'), 'prompt_composition_items', ['composition_id'], unique=False)
    op.create_index(op.f('ix_prompt_composition_items_template_id'), 'prompt_composition_items', ['template_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'resolved', 'rejected', name='report_status_enum'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_target_id'), 'reports', ['target_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('total_days', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('total_price_status', sa.Enum('fresh', 'stale', 'expired', 'unavailable', name='route_price_status_enum'), server_default='fresh', nullable=False),
    sa.Column('total_experiences', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_hotels', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_transports', sa.Integer(), server_default='0', nullable=False),
    sa.Column('share_token', sa.String(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scoring', 'flights', 'distances', 'enriching', 'events', 'weather', 'narrating', 'ready', 'stale', 'booking', 'partially_booked', 'booked', 'completed', 'cancelled', name='route_status_enum'), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_author_id'), 'routes', ['author_id'], unique=False)
    op.create_index(op.f('ix_routes_share_token'), 'routes', ['share_token'], unique=True)
    op.create_table('transport_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_id', sa.BigInteger(), nullable=False),
    sa.Column('to_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('price_from', sa.Integer(), nullable=True),
    sa.Column('aviasales_url', sa.String(), nullable=True),
    sa.Column('tutu_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('plane', 'train', 'bus', 'ferry')", name='transport_links_kind_check'),
    sa.ForeignKeyConstraint(['from_id'], ['geo_regions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['geo_regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', 'kind', name='uq_transport_links_from_to_kind')
    )
    op.create_index(op.f('ix_transport_links_from_id'), 'transport_links', ['from_id'], unique=False)
    op.create_index(op.f('ix_transport_links_to_id'), 'transport_links', ['to_id'], unique=False)
    op.create_table('user_interests',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'interest_id')
    )
    op.create_table('user_saved_routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=False),
    sa.Column('start_lng', sa.Float(), nullable=False),
    sa.Column('start_label', sa.String(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ai_route_meta', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_saved_routes_user_id'), 'user_saved_routes', ['user_id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('follower_id != following_id', name='ck_user_subscriptions_no_self'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    op.create_table('user_tags',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tag_id')
    )
    op.create_table('weather_monthly',
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('rain_mm', sa.Float(), nullable=True),
    sa.Column('sunny_days', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='weather_monthly_month_check'),
    sa.ForeignKeyConstraint(['region_id'], ['geo_regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('region_id', 'month')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'paid', 'cancelled', 'refunded', name='booking_status_enum'), server_default='pending', nullable=False),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_route_id'), 'bookings', ['route_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_post_id'), 'events', ['post_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_post_id'), 'offers', ['post_id'], unique=False)
    op.create_table('place_schedule_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_schedule_overrides_post_id'), 'place_schedule_overrides', ['post_id'], unique=False)
    op.create_table('place_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='ck_place_schedules_day_of_week'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_schedules_post_id'), 'place_schedules', ['post_id'], unique=False)
    op.create_table('place_tags',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.create_table('post_interests',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'interest_id')
    )
    op.create_table('post_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('alt', sa.String(), nullable=True),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_media_post_id'), 'post_media', ['post_id'], unique=False)
    op.create_table('prompt_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('composition_id', sa.Integer(), nullable=True),
    sa.Column('template_ids', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('assembled_prompt', sa.Text(), nullable=True),
    sa.Column('llm_response', sa.Text(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['composition_id'], ['prompt_compositions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_logs_composition_id'), 'prompt_logs', ['composition_id'], unique=False)
    op.create_index(op.f('ix_prompt_logs_route_id'), 'prompt_logs', ['route_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('media_urls', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_reviews_rating_1_5'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id', 'post_id', name='uq_review_per_user_post')
    )
    op.create_index(op.f('ix_reviews_author_id'), 'reviews', ['author_id'], unique=False)
    op.create_index(op.f('ix_reviews_post_id'), 'reviews', ['post_id'], unique=False)
    op.create_table('route_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['geo_regions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_segments_city_id'), 'route_segments', ['city_id'], unique=False)
    op.create_index(op.f('ix_route_segments_route_id'), 'route_segments', ['route_id'], unique=False)
    op.create_table('similar_places',
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('similar_place_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['similar_place_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('place_id', 'similar_place_id')
    )
    op.create_table('tours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('max_group_size', sa.Integer(), nullable=True),
    sa.Column('guide_id', sa.Integer(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publisher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tours_guide_id'), 'tours', ['guide_id'], unique=False)
    op.create_index(op.f('ix_tours_post_id'), 'tours', ['post_id'], unique=False)
    op.create_index(op.f('ix_tours_publisher_id'), 'tours', ['publisher_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
    )
    op.create_table('user_place_statuses',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('visited', 'want', 'planned', name='place_status_enum'), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('user_saved_route_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['user_saved_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'position', name='uq_user_saved_route_position'),
    sa.UniqueConstraint('route_id', 'post_id', name='uq_user_saved_route_post')
    )
    op.create_index(op.f('ix_user_saved_route_items_post_id'), 'user_saved_route_items', ['post_id'], unique=False)
    op.create_index(op.f('ix_user_saved_route_items_route_id'), 'user_saved_route_items', ['route_id'], unique=False)
    op.create_table('user_swiped_posts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('left', 'right', 'up', name='swipe_direction_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('segment_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('leg', 'stay', 'transfer', 'car_rental', 'day', 'experience', name='segment_item_type_enum'), nullable=False),
    sa.Column('position', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_currency', sa.String(length=3), nullable=True),
    sa.Column('price_original', sa.Float(), nullable=True),
    sa.Column('price_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_status', sa.Enum('fresh', 'stale', 'expired', 'unavailable', name='segment_item_price_status_enum'), server_default='fresh', nullable=False),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('provider_url', sa.String(), nullable=True),
    sa.Column('ai_comment', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['segment_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['segment_id'], ['route_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segment_items_parent_id'), 'segment_items', ['parent_id'], unique=False)
    op.create_index(op.f('ix_segment_items_segment_id'), 'segment_items', ['segment_id'], unique=False)
    op.create_table('tour_services',
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tour_id', 'service_id')
    )
    op.create_table('booking_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('segment_item_id', sa.Integer(), nullable=False),
    sa.Column('external_booking_ref', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'failed', 'cancelled', 'refunded', name='booking_item_status_enum'), server_default='pending', nullable=False),
    sa.Column('price_locked', sa.Float(), nullable=True),
    sa.Column('confirmation_url', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_item_id'], ['segment_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_items_booking_id'), 'booking_items', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_items_segment_item_id'), 'booking_items', ['segment_item_id'], unique=False)
    op.create_table('route_pins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('segment_item_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('pin_type', sa.Enum('city', 'stay', 'experience', 'transport_hub', 'photo_spot', 'food', 'custom', name='pin_type_enum'), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('zoom_level', sa.SmallInteger(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('source', sa.Enum('auto', 'user', 'editor', 'ai', name='pin_source_enum'), server_default='auto', nullable=False),
    sa.Column('is_persistent', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['route_segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['segment_item_id'], ['segment_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_pins_created_by'), 'route_pins', ['created_by'], unique=False)
    op.create_index(op.f('ix_route_pins_route_id'), 'route_pins', ['route_id'], unique=False)
    op.create_index(op.f('ix_route_pins_segment_id'), 'route_pins', ['segment_id'], unique=False)
    op.create_index(op.f('ix_route_pins_segment_item_id'), 'route_pins', ['segment_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_pins_segment_item_id'), table_name='route_pins')
    op.drop_index(op.f('ix_route_pins_segment_id'), table_name='route_pins')
    op.drop_index(op.f('ix_route_pins_route_id'), table_name='route_pins')
    op.drop_index(op.f('ix_route_pins_created_by'), table_name='route_pins')
    op.drop_table('route_pins')
    op.drop_index(op.f('ix_booking_items_segment_item_id'), table_name='booking_items')
    op.drop_index(op.f('ix_booking_items_booking_id'), table_name='booking_items')
    op.drop_table('booking_items')
    op.drop_table('tour_services')
    op.drop_index(op.f('ix_segment_items_segment_id'), table_name='segment_items')
    op.drop_index(op.f('ix_segment_items_parent_id'), table_name='segment_items')
    op.drop_table('segment_items')
    op.drop_table('user_swiped_posts')
    op.drop_index(op.f('ix_user_saved_route_items_route_id'), table_name='user_saved_route_items')
    op.drop_index(op.f('ix_user_saved_route_items_post_id'), table_name='user_saved_route_items')
    op.drop_table('user_saved_route_items')
    op.drop_table('user_place_statuses')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_tours_publisher_id'), table_name='tours')
    op.drop_index(op.f('ix_tours_post_id'), table_name='tours')
    op.drop_index(op.f('ix_tours_guide_id'), table_name='tours')
    op.drop_table('tours')
    op.drop_table('similar_places')
    op.drop_index(op.f('ix_route_segments_route_id'), table_name='route_segments')
    op.drop_index(op.f('ix_route_segments_city_id'), table_name='route_segments')
    op.drop_table('route_segments')
    op.drop_index(op.f('ix_reviews_post_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_author_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_prompt_logs_route_id'), table_name='prompt_logs')
    op.drop_index(op.f('ix_prompt_logs_composition_id'), table_name='prompt_logs')
    op.drop_table('prompt_logs')
    op.drop_index(op.f('ix_post_media_post_id'), table_name='post_media')
    op.drop_table('post_media')
    op.drop_table('post_interests')
    op.drop_table('place_tags')
    op.drop_index(op.f('ix_place_schedules_post_id'), table_name='place_schedules')
    op.drop_table('place_schedules')
    op.drop_index(op.f('ix_place_schedule_overrides_post_id'), table_name='place_schedule_overrides')
    op.drop_table('place_schedule_overrides')
    op.drop_index(op.f('ix_offers_post_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_events_post_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_route_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('weather_monthly')
    op.drop_table('user_tags')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_user_saved_routes_user_id'), table_name='user_saved_routes')
    op.drop_table('user_saved_routes')
    op.drop_table('user_interests')
    op.drop_index(op.f('ix_transport_links_to_id'), table_name='transport_links')
    op.drop_index(op.f('ix_transport_links_from_id'), table_name='transport_links')
    op.drop_table('transport_links')
    op.drop_index(op.f('ix_routes_share_token'), table_name='routes')
    op.drop_index(op.f('ix_routes_author_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_reports_target_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_prompt_composition_items_template_id'), table_name='prompt_composition_items')
    op.drop_index(op.f('ix_prompt_composition_items_composition_id'), table_name='prompt_composition_items')
    op.drop_table('prompt_composition_items')
    op.drop_index(op.f('ix_posts_region_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_partner_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_invites_inviter_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_invitee_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_code'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_filter_presets_user_id'), table_name='filter_presets')
    op.drop_table('filter_presets')
    op.drop_index(op.f('ix_experts_user_id'), table_name='experts')
    op.drop_index(op.f('ix_experts_region_id'), table_name='experts')
    op.drop_table('experts')
    op.drop_index(op.f('ix_achievements_interest_id'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('services')
    op.drop_index(op.f('ix_prompt_templates_slug'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_category'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_table('prompt_compositions')
    op.drop_index(op.f('ix_interests_name'), table_name='interests')
    op.drop_index(op.f('ix_interests_emoji'), table_name='interests')
    op.drop_table('interests')
    op.drop_index(op.f('ix_geo_regions_parent_id'), table_name='geo_regions')
    op.drop_table('geo_regions')
    # ### end Alembic commands ###
